# Generated by Django 3.1.6 on 2021-08-27 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('f_psychology', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('f_prepregnancy', models.DecimalField(decimal_places=2, default=0.5, max_digits=7)),
                ('f_research', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('f_placenta', models.DecimalField(decimal_places=1, default=0.9, max_digits=7)),
                ('f_medication', models.DecimalField(decimal_places=2, default=0.7, max_digits=7)),
                ('f_fetus', models.DecimalField(decimal_places=2, default=0.3, max_digits=7)),
                ('f_communication', models.DecimalField(decimal_places=2, default=0.7, max_digits=7)),
                ('f_risks', models.DecimalField(decimal_places=2, default=0.9, max_digits=7)),
                ('f_breastfeed', models.DecimalField(decimal_places=2, default=0.3, max_digits=7)),
                ('f_bleeding', models.DecimalField(decimal_places=2, default=0.6, max_digits=7)),
                ('f_tools', models.DecimalField(decimal_places=2, default=0.2, max_digits=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
