# Generated by Django 3.0.2 on 2020-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='features',
            field=models.TextField(default='{""Psychological Distress"": 0.0, ""Pre-Pregnancy"": 0.07317073170731707, ""Research"": 0.0, ""Retained Placenta"": 0.2926829268292683, ""Administer Medication"": 0.12195121951219512, ""Fetal"": 0.0975609756097561, ""Communication"": 0.0, ""Breastfeeding"": 0.0, ""Assess Risks"": 0.0, ""Post-Natal Complications: Bleeding"": 0.24390243902439024, ""Tool Knowledge"": 0.17073170731707318}'),
        ),
    ]
