# Generated by Django 3.0.3 on 2020-02-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200127_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='f_bleeding',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_breastfeed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_communication',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_fetus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_medication',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_placenta',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_prepregnancy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_psychology',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_research',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_risks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='practice',
            name='f_tools',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
