# Generated by Django 3.0.2 on 2020-01-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_content_item_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(max_length=100)),
                ('source_url', models.TextField()),
                ('topics', models.TextField()),
                ('text', models.TextField()),
                ('images', models.TextField()),
            ],
        ),
    ]
