# Generated by Django 3.0.3 on 2020-02-24 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddy', '0002_auto_20200222_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='recommendedbuddies',
            name='slug',
        ),
        migrations.CreateModel(
            name='BuddyBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buddy_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_1', to=settings.AUTH_USER_MODEL)),
                ('buddy_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_2', to=settings.AUTH_USER_MODEL)),
                ('buddy_content', models.ManyToManyField(blank=True, related_name='buddy_content', to='buddy.ContentID')),
            ],
        ),
    ]
